
all_labels = [
    'L-N RMS 1/2 (1-cyc) Min(V)',
    'L-N RMS 1/2 (1-cyc) Avg(V)',
    'L-N RMS 1/2 (1-cyc) Max(V)',
    'L-N RMS 10-Cycle Min(V)',
    'L-N RMS 10-Cycle Avg(V)',
    'L-N RMS 10-Cycle Max(V)',
    'L-L RMS 1/2 (1-cyc) Min(V)',
    'L-L RMS 1/2 (1-cyc) Avg(V)',
    'L-L RMS 1/2 (1-cyc) Max(V)',
    'L-L RMS 10-Cycle Min(V)',
    'L-L RMS 10-Cycle Avg(V)',
    'L-L RMS 10-Cycle Max(V)',
    'Current RMS 1/2 (1-cyc) Min(A)',
    'Current RMS 1/2 (1-cyc) Avg(A)',
    'Current RMS 1/2 (1-cyc) Max(A)',
    'Current RMS 10-Cycle Min(A)',
    'Current RMS 10-Cycle Avg(A)',
    'Current RMS 10-Cycle Max(A)',
    'Frequency (1-cyc) Min(Hz)',
    'Frequency (1-cyc) Avg(Hz)',
    'Frequency (1-cyc) Max(Hz)',
    'THD-V Min(%)',
    'THD-V Avg(%)',
    'THD-V Max(%)',
    'TDD-A Min(%)',
    'TDD-A Avg(%)',
    'TDD-A Max(%)',
    'IEC Negative Sequence V Min(%)',
    'IEC Negative Sequence V Avg(%)',
    'IEC Negative Sequence V Max(%)',
    'IEC Zero Sequence V Min(%)',
    'IEC Zero Sequence V Avg(%)',
    'IEC Zero Sequence V Max(%)',
    'IEC Negative Sequence A Min(%)',
    'IEC Negative Sequence A Avg(%)',
    'IEC Negative Sequence A Max(%)',
    'IEC Zero Sequence A Min(%)',
    'IEC Zero Sequence A Avg(%)',
    'IEC Zero Sequence A Max(%)',
    'Flicker P(inst) Min',
    'Flicker P(inst) Avg',
    'Flicker P(inst) Max',
    'Flicker P(st) Min',
    'Flicker P(st) Avg',
    'Flicker P(st) Max',
    'Flicker P(lt) Min',
    'Flicker P(lt) Avg',
    'Flicker P(lt) Max',
    'N-E RMS 1/2 (1-cyc) Min(V)',
    'N-E RMS 1/2 (1-cyc) Avg(V)',
    'N-E RMS 1/2 (1-cyc) Max(V)',
    'L1-N RMS 1/2 (1-cyc) Min(V)',
    'L1-N RMS 1/2 (1-cyc) Avg(V)',
    'L1-N RMS 1/2 (1-cyc) Max(V)',
    'L2-N RMS 1/2 (1-cyc) Min(V)',
    'L2-N RMS 1/2 (1-cyc) Avg(V)',
    'L2-N RMS 1/2 (1-cyc) Max(V)',
    'L3-N RMS 1/2 (1-cyc) Min(V)',
    'L3-N RMS 1/2 (1-cyc) Avg(V)',
    'L3-N RMS 1/2 (1-cyc) Max(V)',
    'L1-L2 RMS 1/2 (1-cyc) Min(V)',
    'L1-L2 RMS 1/2 (1-cyc) Avg(V)',
    'L1-L2 RMS 1/2 (1-cyc) Max(V)',
    'L2-L3 RMS 1/2 (1-cyc) Min(V)',
    'L2-L3 RMS 1/2 (1-cyc) Avg(V)',
    'L2-L3 RMS 1/2 (1-cyc) Max(V)',
    'L3-L1 RMS 1/2 (1-cyc) Min(V)',
    'L3-L1 RMS 1/2 (1-cyc) Avg(V)',
    'L3-L1 RMS 1/2 (1-cyc) Max(V)',
    'L1 Current RMS 1/2 (1-cyc) Min(A)',
    'L1 Current RMS 1/2 (1-cyc) Avg(A)',
    'L1 Current RMS 1/2 (1-cyc) Max(A)',
    'L2 Current RMS 1/2 (1-cyc) Min(A)',
    'L2 Current RMS 1/2 (1-cyc) Avg(A)',
    'L2 Current RMS 1/2 (1-cyc) Max(A)',
    'L3 Current RMS 1/2 (1-cyc) Min(A)',
    'L3 Current RMS 1/2 (1-cyc) Avg(A)',
    'L3 Current RMS 1/2 (1-cyc) Max(A)',
    'N Current RMS 1/2 (1-cyc) Min(A)',
    'N Current RMS 1/2 (1-cyc) Avg(A)',
    'N Current RMS 1/2 (1-cyc) Max(A)',
    'E Current RMS 1/2 (1-cyc) Min(A)',
    'E Current RMS 1/2 (1-cyc) Avg(A)',
    'E Current RMS 1/2 (1-cyc) Max(A)',
    'THD-V L1 Min(%)',
    'THD-V L1 Avg(%)',
    'THD-V L1 Max(%)',
    'THD-V L2 Min(%)',
    'THD-V L2 Avg(%)',
    'THD-V L2 Max(%)',
    'THD-V L3 Min(%)',
    'THD-V L3 Avg(%)',
    'THD-V L3 Max(%)',
    'TDD-A L1 Min(%)',
    'TDD-A L1 Avg(%)',
    'TDD-A L1 Max(%)',
    'TDD-A L2 Min(%)',
    'TDD-A L2 Avg(%)',
    'TDD-A L2 Max(%)',
    'TDD-A L3 Min(%)',
    'TDD-A L3 Avg(%)',
    'TDD-A L3 Max(%)',
    'P(inst) L1 Min',
    'P(inst) L1 Avg',
    'P(inst) L1 Max',
    'P(inst) L2 Min',
    'P(inst) L2 Avg',
    'P(inst) L2 Max',
    'P(inst) L3 Min',
    'P(inst) L3 Avg',
    'P(inst) L3 Max',
    'P(st) L1 Min',
    'P(st) L1 Avg',
    'P(st) L1 Max',
    'P(st) L2 Min',
    'P(st) L2 Avg',
    'P(st) L2 Max',
    'P(st) L3 Min',
    'P(st) L3 Avg',
    'P(st) L3 Max',
    'P(lt) L1 Min',
    'P(lt) L1 Avg',
    'P(lt) L1 Max',
    'P(lt) L2 Min',
    'P(lt) L2 Avg',
    'P(lt) L2 Max',
    'P(lt) L3 Min',
    'P(lt) L3 Avg',
    'P(lt) L3 Max',
    'Apparent Power 10-Cycle Min(kVA)',
    'Apparent Power 10-Cycle Avg(kVA)',
    'Apparent Power 10-Cycle Max(kVA)',
    'Reactive Power 10-Cycle Min(kVAR)',
    'Reactive Power 10-Cycle Avg(kVAR)',
    'Reactive Power 10-Cycle Max(kVAR)',
    'Real Power 10-Cycle Min(kW)',
    'Real Power 10-Cycle Avg(kW)',
    'Real Power 10-Cycle Max(kW)',
    'tPF 10-Cycle Min',
    'tPF 10-Cycle Avg',
    'tPF 10-Cycle Max',
    'Carbon Rate 10-Cycle Min(kg/h)',
    'Carbon Rate 10-Cycle Avg(kg/h)',
    'Carbon Rate 10-Cycle Max(kg/h)',
    'VA L1 10-Cycle Min(kVA)',
    'VA L1 10-Cycle Avg(kVA)',
    'VA L1 10-Cycle Max(kVA)',
    'VA L2 10-Cycle Min(kVA)',
    'VA L2 10-Cycle Avg(kVA)',
    'VA L2 10-Cycle Max(kVA)',
    'VA L3 10-Cycle Min(kVA)',
    'VA L3 10-Cycle Avg(kVA)',
    'VA L3 10-Cycle Max(kVA)',
    'VAR L1 10-Cycle Min(kVAR)',
    'VAR L1 10-Cycle Avg(kVAR)',
    'VAR L1 10-Cycle Max(kVAR)',
    'VAR L2 10-Cycle Min(kVAR)',
    'VAR L2 10-Cycle Avg(kVAR)',
    'VAR L2 10-Cycle Max(kVAR)',
    'VAR L3 10-Cycle Min(kVAR)',
    'VAR L3 10-Cycle Avg(kVAR)',
    'VAR L3 10-Cycle Max(kVAR)',
    'Real Power L1 10-Cycle Min(kW)',
    'Real Power L1 10-Cycle Avg(kW)',
    'Real Power L1 10-Cycle Max(kW)',
    'Real Power L2 10-Cycle Min(kW)',
    'Real Power L2 10-Cycle Avg(kW)',
    'Real Power L2 10-Cycle Max(kW)',
    'Real Power L3 10-Cycle Min(kW)',
    'Real Power L3 10-Cycle Avg(kW)',
    'Real Power L3 10-Cycle Max(kW)',
    'tPF L1 10-Cycle Min',
    'tPF L1 10-Cycle Avg',
    'tPF L1 10-Cycle Max',
    'tPF L2 10-Cycle Min',
    'tPF L2 10-Cycle Avg',
    'tPF L2 10-Cycle Max',
    'tPF L3 10-Cycle Min',
    'tPF L3 10-Cycle Avg',
    'tPF L3 10-Cycle Max',
    'Energy (kWH)'
]


all_labels_voltage_harmonics = [
    'H0 Harmonic Amplitude (V)',
    'H0 Harmonic Angle (deg)',
    'H0 Interharmonic (V)',
    'H1 Harmonic Amplitude (V)',
    'H1 Harmonic Angle (deg)',
    'H1 Interharmonic (V)',
    'H2 Harmonic Amplitude (V)',
    'H2 Harmonic Angle (deg)',
    'H2 Interharmonic (V)',
    'H3 Harmonic Amplitude (V)',
    'H3 Harmonic Angle (deg)',
    'H3 Interharmonic (V)',
    'H4 Harmonic Amplitude (V)',
    'H4 Harmonic Angle (deg)',
    'H4 Interharmonic (V)',
    'H5 Harmonic Amplitude (V)',
    'H5 Harmonic Angle (deg)',
    'H5 Interharmonic (V)',
    'H6 Harmonic Amplitude (V)',
    'H6 Harmonic Angle (deg)',
    'H6 Interharmonic (V)',
    'H7 Harmonic Amplitude (V)',
    'H7 Harmonic Angle (deg)',
    'H7 Interharmonic (V)',
    'H8 Harmonic Amplitude (V)',
    'H8 Harmonic Angle (deg)',
    'H8 Interharmonic (V)',
    'H9 Harmonic Amplitude (V)',
    'H9 Harmonic Angle (deg)',
    'H9 Interharmonic (V)',
    'H10 Harmonic Amplitude (V)',
    'H10 Harmonic Angle (deg)',
    'H10 Interharmonic (V)',
    'H11 Harmonic Amplitude (V)',
    'H11 Harmonic Angle (deg)',
    'H11 Interharmonic (V)',
    'H12 Harmonic Amplitude (V)',
    'H12 Harmonic Angle (deg)',
    'H12 Interharmonic (V)',
    'H13 Harmonic Amplitude (V)',
    'H13 Harmonic Angle (deg)',
    'H13 Interharmonic (V)',
    'H14 Harmonic Amplitude (V)',
    'H14 Harmonic Angle (deg)',
    'H14 Interharmonic (V)',
    'H15 Harmonic Amplitude (V)',
    'H15 Harmonic Angle (deg)',
    'H15 Interharmonic (V)',
    'H16 Harmonic Amplitude (V)',
    'H16 Harmonic Angle (deg)',
    'H16 Interharmonic (V)',
    'H17 Harmonic Amplitude (V)',
    'H17 Harmonic Angle (deg)',
    'H17 Interharmonic (V)',
    'H18 Harmonic Amplitude (V)',
    'H18 Harmonic Angle (deg)',
    'H18 Interharmonic (V)',
    'H19 Harmonic Amplitude (V)',
    'H19 Harmonic Angle (deg)',
    'H19 Interharmonic (V)',
    'H20 Harmonic Amplitude (V)',
    'H20 Harmonic Angle (deg)',
    'H20 Interharmonic (V)',
    'H21 Harmonic Amplitude (V)',
    'H21 Harmonic Angle (deg)',
    'H21 Interharmonic (V)',
    'H22 Harmonic Amplitude (V)',
    'H22 Harmonic Angle (deg)',
    'H22 Interharmonic (V)',
    'H23 Harmonic Amplitude (V)',
    'H23 Harmonic Angle (deg)',
    'H23 Interharmonic (V)',
    'H24 Harmonic Amplitude (V)',
    'H24 Harmonic Angle (deg)',
    'H24 Interharmonic (V)',
    'H25 Harmonic Amplitude (V)',
    'H25 Harmonic Angle (deg)',
    'H25 Interharmonic (V)',
    'H26 Harmonic Amplitude (V)',
    'H26 Harmonic Angle (deg)',
    'H26 Interharmonic (V)',
    'H27 Harmonic Amplitude (V)',
    'H27 Harmonic Angle (deg)',
    'H27 Interharmonic (V)',
    'H28 Harmonic Amplitude (V)',
    'H28 Harmonic Angle (deg)',
    'H28 Interharmonic (V)',
    'H29 Harmonic Amplitude (V)',
    'H29 Harmonic Angle (deg)',
    'H29 Interharmonic (V)',
    'H30 Harmonic Amplitude (V)',
    'H30 Harmonic Angle (deg)',
    'H30 Interharmonic (V)',
    'H31 Harmonic Amplitude (V)',
    'H31 Harmonic Angle (deg)',
    'H31 Interharmonic (V)',
    'H32 Harmonic Amplitude (V)',
    'H32 Harmonic Angle (deg)',
    'H32 Interharmonic (V)',
    'H33 Harmonic Amplitude (V)',
    'H33 Harmonic Angle (deg)',
    'H33 Interharmonic (V)',
    'H34 Harmonic Amplitude (V)',
    'H34 Harmonic Angle (deg)',
    'H34 Interharmonic (V)',
    'H35 Harmonic Amplitude (V)',
    'H35 Harmonic Angle (deg)',
    'H35 Interharmonic (V)',
    'H36 Harmonic Amplitude (V)',
    'H36 Harmonic Angle (deg)',
    'H36 Interharmonic (V)',
    'H37 Harmonic Amplitude (V)',
    'H37 Harmonic Angle (deg)',
    'H37 Interharmonic (V)',
    'H38 Harmonic Amplitude (V)',
    'H38 Harmonic Angle (deg)',
    'H38 Interharmonic (V)',
    'H39 Harmonic Amplitude (V)',
    'H39 Harmonic Angle (deg)',
    'H39 Interharmonic (V)',
    'H40 Harmonic Amplitude (V)',
    'H40 Harmonic Angle (deg)',
    'H40 Interharmonic (V)',
    'H41 Harmonic Amplitude (V)',
    'H41 Harmonic Angle (deg)',
    'H41 Interharmonic (V)',
    'H42 Harmonic Amplitude (V)',
    'H42 Harmonic Angle (deg)',
    'H42 Interharmonic (V)',
    'H43 Harmonic Amplitude (V)',
    'H43 Harmonic Angle (deg)',
    'H43 Interharmonic (V)',
    'H44 Harmonic Amplitude (V)',
    'H44 Harmonic Angle (deg)',
    'H44 Interharmonic (V)',
    'H45 Harmonic Amplitude (V)',
    'H45 Harmonic Angle (deg)',
    'H45 Interharmonic (V)',
    'H46 Harmonic Amplitude (V)',
    'H46 Harmonic Angle (deg)',
    'H46 Interharmonic (V)',
    'H47 Harmonic Amplitude (V)',
    'H47 Harmonic Angle (deg)',
    'H47 Interharmonic (V)',
    'H48 Harmonic Amplitude (V)',
    'H48 Harmonic Angle (deg)',
    'H48 Interharmonic (V)',
    'H49 Harmonic Amplitude (V)',
    'H49 Harmonic Angle (deg)',
    'H49 Interharmonic (V)',
    'H50 Harmonic Amplitude (V)',
    'H50 Harmonic Angle (deg)',
    'H50 Interharmonic (V)',
    'H51 Harmonic Amplitude (V)',
    'H51 Harmonic Angle (deg)',
    'H51 Interharmonic (V)',
    'H52 Harmonic Amplitude (V)',
    'H52 Harmonic Angle (deg)',
    'H52 Interharmonic (V)',
    'H53 Harmonic Amplitude (V)',
    'H53 Harmonic Angle (deg)',
    'H53 Interharmonic (V)',
    'H54 Harmonic Amplitude (V)',
    'H54 Harmonic Angle (deg)',
    'H54 Interharmonic (V)',
    'H55 Harmonic Amplitude (V)',
    'H55 Harmonic Angle (deg)',
    'H55 Interharmonic (V)',
    'H56 Harmonic Amplitude (V)',
    'H56 Harmonic Angle (deg)',
    'H56 Interharmonic (V)',
    'H57 Harmonic Amplitude (V)',
    'H57 Harmonic Angle (deg)',
    'H57 Interharmonic (V)',
    'H58 Harmonic Amplitude (V)',
    'H58 Harmonic Angle (deg)',
    'H58 Interharmonic (V)',
    'H59 Harmonic Amplitude (V)',
    'H59 Harmonic Angle (deg)',
    'H59 Interharmonic (V)',
    'H60 Harmonic Amplitude (V)',
    'H60 Harmonic Angle (deg)',
    'H60 Interharmonic (V)',
    'H61 Harmonic Amplitude (V)',
    'H61 Harmonic Angle (deg)',
    'H61 Interharmonic (V)',
    'H62 Harmonic Amplitude (V)',
    'H62 Harmonic Angle (deg)',
    'H62 Interharmonic (V)',
    'H63 Harmonic Amplitude (V)',
    'H63 Harmonic Angle (deg)',
    'H63 Interharmonic (V)'
]


all_labels_current_harmonics = [
    'H0 Harmonic Amplitude (A)',
    'H0 Harmonic Angle (deg)',
    'H0 Interharmonic (A)',
    'H1 Harmonic Amplitude (A)',
    'H1 Harmonic Angle (deg)',
    'H1 Interharmonic (A)',
    'H2 Harmonic Amplitude (A)',
    'H2 Harmonic Angle (deg)',
    'H2 Interharmonic (A)',
    'H3 Harmonic Amplitude (A)',
    'H3 Harmonic Angle (deg)',
    'H3 Interharmonic (A)',
    'H4 Harmonic Amplitude (A)',
    'H4 Harmonic Angle (deg)',
    'H4 Interharmonic (A)',
    'H5 Harmonic Amplitude (A)',
    'H5 Harmonic Angle (deg)',
    'H5 Interharmonic (A)',
    'H6 Harmonic Amplitude (A)',
    'H6 Harmonic Angle (deg)',
    'H6 Interharmonic (A)',
    'H7 Harmonic Amplitude (A)',
    'H7 Harmonic Angle (deg)',
    'H7 Interharmonic (A)',
    'H8 Harmonic Amplitude (A)',
    'H8 Harmonic Angle (deg)',
    'H8 Interharmonic (A)',
    'H9 Harmonic Amplitude (A)',
    'H9 Harmonic Angle (deg)',
    'H9 Interharmonic (A)',
    'H10 Harmonic Amplitude (A)',
    'H10 Harmonic Angle (deg)',
    'H10 Interharmonic (A)',
    'H11 Harmonic Amplitude (A)',
    'H11 Harmonic Angle (deg)',
    'H11 Interharmonic (A)',
    'H12 Harmonic Amplitude (A)',
    'H12 Harmonic Angle (deg)',
    'H12 Interharmonic (A)',
    'H13 Harmonic Amplitude (A)',
    'H13 Harmonic Angle (deg)',
    'H13 Interharmonic (A)',
    'H14 Harmonic Amplitude (A)',
    'H14 Harmonic Angle (deg)',
    'H14 Interharmonic (A)',
    'H15 Harmonic Amplitude (A)',
    'H15 Harmonic Angle (deg)',
    'H15 Interharmonic (A)',
    'H16 Harmonic Amplitude (A)',
    'H16 Harmonic Angle (deg)',
    'H16 Interharmonic (A)',
    'H17 Harmonic Amplitude (A)',
    'H17 Harmonic Angle (deg)',
    'H17 Interharmonic (A)',
    'H18 Harmonic Amplitude (A)',
    'H18 Harmonic Angle (deg)',
    'H18 Interharmonic (A)',
    'H19 Harmonic Amplitude (A)',
    'H19 Harmonic Angle (deg)',
    'H19 Interharmonic (A)',
    'H20 Harmonic Amplitude (A)',
    'H20 Harmonic Angle (deg)',
    'H20 Interharmonic (A)',
    'H21 Harmonic Amplitude (A)',
    'H21 Harmonic Angle (deg)',
    'H21 Interharmonic (A)',
    'H22 Harmonic Amplitude (A)',
    'H22 Harmonic Angle (deg)',
    'H22 Interharmonic (A)',
    'H23 Harmonic Amplitude (A)',
    'H23 Harmonic Angle (deg)',
    'H23 Interharmonic (A)',
    'H24 Harmonic Amplitude (A)',
    'H24 Harmonic Angle (deg)',
    'H24 Interharmonic (A)',
    'H25 Harmonic Amplitude (A)',
    'H25 Harmonic Angle (deg)',
    'H25 Interharmonic (A)',
    'H26 Harmonic Amplitude (A)',
    'H26 Harmonic Angle (deg)',
    'H26 Interharmonic (A)',
    'H27 Harmonic Amplitude (A)',
    'H27 Harmonic Angle (deg)',
    'H27 Interharmonic (A)',
    'H28 Harmonic Amplitude (A)',
    'H28 Harmonic Angle (deg)',
    'H28 Interharmonic (A)',
    'H29 Harmonic Amplitude (A)',
    'H29 Harmonic Angle (deg)',
    'H29 Interharmonic (A)',
    'H30 Harmonic Amplitude (A)',
    'H30 Harmonic Angle (deg)',
    'H30 Interharmonic (A)',
    'H31 Harmonic Amplitude (A)',
    'H31 Harmonic Angle (deg)',
    'H31 Interharmonic (A)',
    'H32 Harmonic Amplitude (A)',
    'H32 Harmonic Angle (deg)',
    'H32 Interharmonic (A)',
    'H33 Harmonic Amplitude (A)',
    'H33 Harmonic Angle (deg)',
    'H33 Interharmonic (A)',
    'H34 Harmonic Amplitude (A)',
    'H34 Harmonic Angle (deg)',
    'H34 Interharmonic (A)',
    'H35 Harmonic Amplitude (A)',
    'H35 Harmonic Angle (deg)',
    'H35 Interharmonic (A)',
    'H36 Harmonic Amplitude (A)',
    'H36 Harmonic Angle (deg)',
    'H36 Interharmonic (A)',
    'H37 Harmonic Amplitude (A)',
    'H37 Harmonic Angle (deg)',
    'H37 Interharmonic (A)',
    'H38 Harmonic Amplitude (A)',
    'H38 Harmonic Angle (deg)',
    'H38 Interharmonic (A)',
    'H39 Harmonic Amplitude (A)',
    'H39 Harmonic Angle (deg)',
    'H39 Interharmonic (A)',
    'H40 Harmonic Amplitude (A)',
    'H40 Harmonic Angle (deg)',
    'H40 Interharmonic (A)',
    'H41 Harmonic Amplitude (A)',
    'H41 Harmonic Angle (deg)',
    'H41 Interharmonic (A)',
    'H42 Harmonic Amplitude (A)',
    'H42 Harmonic Angle (deg)',
    'H42 Interharmonic (A)',
    'H43 Harmonic Amplitude (A)',
    'H43 Harmonic Angle (deg)',
    'H43 Interharmonic (A)',
    'H44 Harmonic Amplitude (A)',
    'H44 Harmonic Angle (deg)',
    'H44 Interharmonic (A)',
    'H45 Harmonic Amplitude (A)',
    'H45 Harmonic Angle (deg)',
    'H45 Interharmonic (A)',
    'H46 Harmonic Amplitude (A)',
    'H46 Harmonic Angle (deg)',
    'H46 Interharmonic (A)',
    'H47 Harmonic Amplitude (A)',
    'H47 Harmonic Angle (deg)',
    'H47 Interharmonic (A)',
    'H48 Harmonic Amplitude (A)',
    'H48 Harmonic Angle (deg)',
    'H48 Interharmonic (A)',
    'H49 Harmonic Amplitude (A)',
    'H49 Harmonic Angle (deg)',
    'H49 Interharmonic (A)',
    'H50 Harmonic Amplitude (A)',
    'H50 Harmonic Angle (deg)',
    'H50 Interharmonic (A)',
    'H51 Harmonic Amplitude (A)',
    'H51 Harmonic Angle (deg)',
    'H51 Interharmonic (A)',
    'H52 Harmonic Amplitude (A)',
    'H52 Harmonic Angle (deg)',
    'H52 Interharmonic (A)',
    'H53 Harmonic Amplitude (A)',
    'H53 Harmonic Angle (deg)',
    'H53 Interharmonic (A)',
    'H54 Harmonic Amplitude (A)',
    'H54 Harmonic Angle (deg)',
    'H54 Interharmonic (A)',
    'H55 Harmonic Amplitude (A)',
    'H55 Harmonic Angle (deg)',
    'H55 Interharmonic (A)',
    'H56 Harmonic Amplitude (A)',
    'H56 Harmonic Angle (deg)',
    'H56 Interharmonic (A)',
    'H57 Harmonic Amplitude (A)',
    'H57 Harmonic Angle (deg)',
    'H57 Interharmonic (A)',
    'H58 Harmonic Amplitude (A)',
    'H58 Harmonic Angle (deg)',
    'H58 Interharmonic (A)',
    'H59 Harmonic Amplitude (A)',
    'H59 Harmonic Angle (deg)',
    'H59 Interharmonic (A)',
    'H60 Harmonic Amplitude (A)',
    'H60 Harmonic Angle (deg)',
    'H60 Interharmonic (A)',
    'H61 Harmonic Amplitude (A)',
    'H61 Harmonic Angle (deg)',
    'H61 Interharmonic (A)',
    'H62 Harmonic Amplitude (A)',
    'H62 Harmonic Angle (deg)',
    'H62 Interharmonic (A)',
    'H63 Harmonic Amplitude (A)',
    'H63 Harmonic Angle (deg)',
    'H63 Interharmonic (A)'
]


all_labels_events = [
    'Milliseconds',
    'N-E (V)',
    'L1-N (V)',
    'L2-N (V)',
    'L3-N (V)',
    'L1 Amp (A)',
    'L2 Amp (A)',
    'L3 Amp (A)',
    'N Amp (A)'
]

def new_name(old, harmonic=False):
    if harmonic:
        return old.replace(' (A)', '').replace(' (V)', '').replace(' (deg)', '').replace(' Harmonic', '').replace(' Interharmonic', '_inter_mag').replace(' Amplitude', '_mag').replace(' Angle', '_ang')
    # return old.replace(' ', '_').replace('(', '_').replace(')', '').replace('/', '_').replace('-', '_').replace('%', 'perc')
    else:
        return old.replace(' ', '_').replace('(', '_').replace(')', '').replace('/', '_').replace('-', '_').replace('%', 'perc')

# def new_name_harmonic(old):
#     return old.replace(' ', '_').replace('(', '_').replace(')', '').replace('/', '_').replace('-', '_').replace('%', 'perc')

def new_labels(labels, harmonic=False, pos_start=None):
    # CSV column labels for data extraction
    for l in labels:
        print '\'' + new_name(l, harmonic) + '\': \'' + l + '\','

    # Pytables column definitions
    if pos_start is not None:
        pos = pos_start
    for l in labels:
        if pos_start is not None:
            print new_name(l, harmonic) + ' = Float32Col(pos=' + str(pos) + ')'
            pos += 1
        else:
            print new_name(l, harmonic) + ' = Float32Col()'


# TODO bug in generating code: 'Max' in wrong place


new_labels(all_labels)
print '\n\n\n\n'
new_labels(all_labels_voltage_harmonics, harmonic=True, pos_start=2)
print '\n\n\n\n'
new_labels(all_labels_current_harmonics, harmonic=True, pos_start=2)
print '\n\n\n\n'
new_labels(all_labels_events, pos_start=9)